DROP TABLE IF EXISTS veterinaires_specialites;
DROP TABLE IF EXISTS visites;
DROP TABLE IF EXISTS animaux;
DROP TABLE IF EXISTS specialites;
DROP TABLE IF EXISTS types_animaux;
DROP TABLE IF EXISTS proprietaires;
DROP TABLE IF EXISTS veterinaires;

CREATE TABLE veterinaires (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prenom VARCHAR(255) NOT NULL,
    nom VARCHAR(255) NOT NULL
);

CREATE TABLE specialites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE veterinaires_specialites (
    veterinaire_id BIGINT NOT NULL,
    specialite_id BIGINT NOT NULL,
    PRIMARY KEY (veterinaire_id, specialite_id),
    CONSTRAINT fk_veterinaires_specialites_veterinaire
        FOREIGN KEY (veterinaire_id) REFERENCES veterinaires (id),
    CONSTRAINT fk_veterinaires_specialites_specialite
        FOREIGN KEY (specialite_id) REFERENCES specialites (id)
);

CREATE TABLE types_animaux (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    libelle VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE proprietaires (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prenom VARCHAR(255) NOT NULL,
    nom VARCHAR(255) NOT NULL,
    adresse VARCHAR(255) NOT NULL,
    ville VARCHAR(255) NOT NULL,
    telephone VARCHAR(255) NOT NULL
);

CREATE TABLE animaux (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    date_naissance DATE NOT NULL,
    type_animal_id BIGINT NOT NULL,
    proprietaire_id BIGINT NOT NULL,
    CONSTRAINT fk_animaux_type_animal
        FOREIGN KEY (type_animal_id) REFERENCES types_animaux (id),
    CONSTRAINT fk_animaux_proprietaire
        FOREIGN KEY (proprietaire_id) REFERENCES proprietaires (id)
);

CREATE TABLE visites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal_id BIGINT NOT NULL,
    date_visite DATE NOT NULL,
    motif VARCHAR(255) NOT NULL,
    CONSTRAINT fk_visites_animal
        FOREIGN KEY (animal_id) REFERENCES animaux (id)
);

CREATE INDEX idx_animaux_type_animal_id ON animaux (type_animal_id);
CREATE INDEX idx_animaux_proprietaire_id ON animaux (proprietaire_id);
CREATE INDEX idx_visites_animal_id ON visites (animal_id);
CREATE INDEX idx_veterinaires_specialites_specialite_id
    ON veterinaires_specialites (specialite_id);
